### PR TITLE
Replace crypto modules with new collection

### LINKED ISSUE #46: Update the role to use community.crypto collections
The standard ansible modules will not be maintained any more so using community.crypto collection will be a big profit

### PR DESCRIPTION
**Pull request by widhalmt**
fixes #46

### CODE REVIEW

**Comment by widhalmt** [comment]
I'm still not totally conviced that using FQCN is worth all the extra work but since it seems we won't be able to work around it, I used the chance to change them all.

**Comment by widhalmt** [comment]
I was hoping this replacement was more or less a "renaming". Since this is not the case, I will keep this PR open and will replace the tasks bit by bit. Might take a bit longer than initially planned. 😬

**Review by afeefghannam89 — DISMISSED** [review]
Some tasks need also changes e.g  line [238](https://github.com/NETWAYS/ansible-role-ca/blob/bc021ad1905e11025b076016c081e5e42e1946b0/tasks/main.yml#L238)

[263](https://github.com/NETWAYS/ansible-role-ca/blob/bc021ad1905e11025b076016c081e5e42e1946b0/tasks/main.yml#L263)

[294](https://github.com/NETWAYS/ansible-role-ca/blob/bc021ad1905e11025b076016c081e5e42e1946b0/tasks/main.yml#L294)

[319](https://github.com/NETWAYS/ansible-role-ca/blob/bc021ad1905e11025b076016c081e5e42e1946b0/tasks/main.yml#L319)

You can also change the calling of noraml ansible module like file to FQCN with addnig ansible.builtin to it like what you made in another tasks

**Review by afeefghannam89 — APPROVED** [review]
Thanks for the changes

**Pull request merged**
